name: Environment の secrets と variables の違いを見るテスト
on: 
    push:
    workflow_dispatch:

env:
  THIS_IS_ENVIRONMENT_SECRETS: ${{ secrets.ENV_SECRETS }}
  THIS_IS_ENVIRONMENT_VARIABLES: ${{ vars.ENV_TEST }}

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: THIS_IS_ENVIRONMENT_SECRETS の 値を表示
        run: echo ${THIS_IS_ENVIRONMENT_SECRETS}

      - name: THIS_IS_ENVIRONMENT_VARIABLES の 値を表示
        run: echo ${THIS_IS_ENVIRONMENT_VARIABLES}